# -*- coding: utf-8 -*-
"""question-0002-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pQ86SuFkjHzprqOqmN7OomYl1sJM8ZEs
"""

import pandas as pd
import numpy as np
import random

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

def generar_caso_de_uso_entrenar_modelo_abandono():
    """
    Genera un caso de prueba aleatorio (input y output esperado)
    para la función entrenar_modelo_abandono.
    """

    # ---------------------------------------------------------
    # 1. Generar datos aleatorios
    # ---------------------------------------------------------
    n_rows = random.randint(30, 80)

    df = pd.DataFrame({
        'edad': np.random.randint(18, 80, size=n_rows),
        'ingreso_mensual': np.round(np.random.uniform(800, 8000, size=n_rows), 2),
        'meses_contrato': np.random.randint(1, 72, size=n_rows),
        'numero_servicios': np.random.randint(1, 6, size=n_rows)
    })

    # Generar target con algo de relación con las variables
    score = (
        0.03 * df['edad']
        - 0.0004 * df['ingreso_mensual']
        - 0.04 * df['meses_contrato']
        + 0.25 * df['numero_servicios']
        + np.random.normal(0, 1, size=n_rows)
    )

    df['abandono'] = (score > np.median(score)).astype(int)
    target_col = 'abandono'

    # ---------------------------------------------------------
    # 2. Construir INPUT
    # ---------------------------------------------------------
    input_data = {
        'df': df.copy(),
        'target_col': target_col
    }

    # ---------------------------------------------------------
    # 3. Calcular OUTPUT esperado (ground truth)
    # ---------------------------------------------------------

    # A. Separar X e y
    X = df.drop(columns=[target_col])
    y = df[target_col].to_numpy()

    # B. Dividir train/test
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # C. Escalar
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # D. Entrenar modelo
    modelo = LogisticRegression(max_iter=1000, random_state=42)
    modelo.fit(X_train_scaled, y_train)

    # E. Evaluar accuracy
    y_pred = modelo.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)

    output_data = (modelo, accuracy)

    return input_data, output_data


# --- Ejemplo de uso ---
if __name__ == "__main__":
    entrada, salida_esperada = generar_caso_de_uso_entrenar_modelo_abandono()

    print("=== INPUT ===")
    print(f"Target Column: {entrada['target_col']}")
    print(entrada['df'].head())

    print("\n=== OUTPUT ESPERADO ===")
    modelo_res, accuracy_res = salida_esperada
    print("Modelo entrenado:", modelo_res)
    print("Accuracy:", accuracy_res)