# -*- coding: utf-8 -*-
"""question-0004-usecase-generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PRQddVc9tCylR5mpdncJOIY9a7K8NWOM
"""

import pandas as pd
import numpy as np
import random

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

def generar_caso_de_uso_entrenar_modelo_precio_vivienda():
    """
    Genera un caso de prueba aleatorio (input y output esperado)
    para la función entrenar_modelo_precio_vivienda.
    """

    # ---------------------------------------------------------
    # 1. Generar datos aleatorios
    # ---------------------------------------------------------
    n_rows = random.randint(30, 80)

    area_m2 = np.random.randint(40, 250, size=n_rows)
    numero_habitaciones = np.random.randint(1, 6, size=n_rows)
    edad_vivienda = np.random.randint(0, 50, size=n_rows)
    distancia_centro = np.round(np.random.uniform(0.5, 25, size=n_rows), 2)

    ruido = np.random.normal(0, 15000, size=n_rows)

    precio = (
        area_m2 * 3000
        + numero_habitaciones * 20000
        - edad_vivienda * 1500
        - distancia_centro * 5000
        + ruido
    )

    df = pd.DataFrame({
        'area_m2': area_m2,
        'numero_habitaciones': numero_habitaciones,
        'edad_vivienda': edad_vivienda,
        'distancia_centro': distancia_centro,
        'precio': np.round(precio, 2)
    })

    target_col = 'precio'

    # ---------------------------------------------------------
    # 2. Construir INPUT
    # ---------------------------------------------------------
    input_data = {
        'df': df.copy(),
        'target_col': target_col
    }

    # ---------------------------------------------------------
    # 3. Calcular OUTPUT esperado (ground truth)
    # ---------------------------------------------------------

    # A. Separar X e y
    X = df.drop(columns=[target_col])
    y = df[target_col].to_numpy()

    # B. Dividir train/test
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # C. Entrenar modelo
    modelo = LinearRegression()
    modelo.fit(X_train, y_train)

    # D. Predecir
    y_pred = modelo.predict(X_test)

    # E. Calcular MSE
    mse = mean_squared_error(y_test, y_pred)

    output_data = (modelo, mse)

    return input_data, output_data


# --- Ejemplo de uso ---
if __name__ == "__main__":
    entrada, salida_esperada = generar_caso_de_uso_entrenar_modelo_precio_vivienda()

    print("=== INPUT ===")
    print(f"Target Column: {entrada['target_col']}")
    print(entrada['df'].head())

    print("\n=== OUTPUT ESPERADO ===")
    modelo_res, mse_res = salida_esperada
    print("Modelo entrenado:", modelo_res)
    print("MSE:", mse_res)