# -*- coding: utf-8 -*-
"""question-0001-usecase-generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDmZ0I-EJqDi_6ym9T9sQ6EmPjrOGn25
"""

import pandas as pd
import numpy as np
import random

def generar_caso_de_uso_resumen_ventas_por_categoria():
    """
    Genera un caso de prueba aleatorio (input y output esperado)
    para la función resumen_ventas_por_categoria.
    """

    # ---------------------------------------------------------
    # 1. Generar datos aleatorios
    # ---------------------------------------------------------
    n_rows = random.randint(5, 15)

    productos = [f'producto_{i}' for i in range(1, 6)]
    categorias = ['A', 'B', 'C']

    df = pd.DataFrame({
        'producto': np.random.choice(productos, size=n_rows),
        'categoria': np.random.choice(categorias, size=n_rows),
        'precio_unitario': np.round(np.random.uniform(5, 100, size=n_rows), 2),
        'cantidad_vendida': np.random.randint(1, 20, size=n_rows)
    })

    # ---------------------------------------------------------
    # 2. Construir INPUT
    # ---------------------------------------------------------
    input_data = {
        'df': df.copy()
    }

    # ---------------------------------------------------------
    # 3. Calcular OUTPUT esperado (ground truth)
    # ---------------------------------------------------------

    # A. Crear ingreso_total
    df_calc = df.copy()
    df_calc['ingreso_total'] = df_calc['precio_unitario'] * df_calc['cantidad_vendida']

    # B. Agrupar por categoría
    resumen = df_calc.groupby('categoria').agg({
        'ingreso_total': 'sum',
        'cantidad_vendida': 'sum',
        'precio_unitario': 'mean'
    }).reset_index()

    # Renombrar columnas si quieres claridad (opcional pero recomendable)
    resumen = resumen.rename(columns={
        'ingreso_total': 'total_ingresos',
        'cantidad_vendida': 'total_unidades',
        'precio_unitario': 'precio_promedio'
    })

    output_data = resumen

    return input_data, output_data


# --- Ejemplo de uso ---
if __name__ == "__main__":
    entrada, salida_esperada = generar_caso_de_uso_resumen_ventas_por_categoria()

    print("=== INPUT ===")
    print(entrada['df'])

    print("\n=== OUTPUT ESPERADO ===")
    print(salida_esperada)